spring:
  ## 默认使用dev分支
  profiles:
    active: dev
  ## 数据源
  datasource:
    ## mysql链接驱动，可不配置。默认从引入的pom中找
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(vdS9MNbdpWPOQRZn/7nP7Q==)
    password: ENC(nb9tQ8Hm2SWrZvsL53uSQUrL0NSWida1)
    ## 批量更新sql需要设置&allowMultiQueries=true
    url: jdbc:mysql://rm-wz9bkwv69su8u0hl3bo.mysql.rds.aliyuncs.com:3306/video?characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    ## 连接池，可不配置。2.x默认使用该连接池
    type: com.zaxxer.hikari.HikariDataSource

## mybatiplus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.duan.video.pojo.entity

rest:
  ReadTimeout=35000:

## 配置文件密码加密
jasypt:
  encryptor:
    password: JXU3NzBCJXU3MjQ3
---
## 开发的配置
spring:
  profiles: dev

## 日志输出，不配置不会输出sql日志
logging:
  level:
    com.duan.video: debug

---
## 生产的配置
spring:
  profiles: prd

## 开启定时任务
scheduling:
  enabled: true

## 日志输出，不配置不会输出sql日志
logging:
  level:
    com.duan.video: debug
